#!/usr/bin/env ruby

SEPARATOR="--"
def split_args(array)
  index = array.find_index { | elt | elt == SEPARATOR}
  if (! index)
    puts "There is no pattern list ending in a `--`."
    exit 1
  end

  [array.slice(0, index), array.slice(index+1..-1)]
end

pattern_args,FILES=split_args(ARGV)
PATTERNS = pattern_args.map { | s | Regexp.compile(s) }

def try_file(f)
  PATTERNS.each do | pattern |
    if pattern =~ f
      puts "Pattern #{p.inspect} prohibits #{f}"
      return 1
    end
  end
  0
end

exit_status = 0
FILES.each do | f |
  exit_status |= try_file(f)
end

exit exit_status
